### ISSUE TITLE
model saving issue at modelcheckpoint

### ISSUE THREAD

**Issue by karim1871** [andreped/GradientAccumulator#134]
Hi, 
Thank you for the your great work,
i have an issue using  GradientAccumulateModel with tensorflow==2.10.1.

At the end of the epoch, with ModelCheckpoint(model_path, verbose=1, monitor = "val_loss",save_best_only=True), i get an error when the model is saved : 
ValueError: Unable to create dataset (name already exists).

Everything is working fine if i don't use : 
model = GradientAccumulateModel(accum_steps=4, inputs=model.input, outputs=model.output, mixed_precision = True)

Same issue with model.save(). The model is saved but the program crashes with the same error: 
  File h5py\h5d.pyx:138 in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)

Any idea?
Thank you

**Comment by andreped** [comment]
Hello, @karim1871! :]

We deprecated support for saving models as HDF5 a while back. There is actually info about this in the documentations here:
https://gradientaccumulator.readthedocs.io/en/latest/faq/model_format.html#model-format

Does it work fine if you change to `/path/to/model/dir/` where this now will be a new folder where the SavedModel will be saved?

We actively run tests to ensure that saving/loading works fine:
https://github.com/andreped/GradientAccumulator/blob/main/tests/utils.py#L156

I actively use ModelCheckpoint for other projects. Should work fine.

Could you try this and let me know how it works. Otherwise, I would need to know more what you are doing to debug this.

**Comment by karim1871** [comment]
Hi, thank you for the quick answer. 
It is working with /path/to/model/dir/.

Have a nice day !

**Comment by andreped** [comment]
> It is working with /path/to/model/dir/.

Great!! :] Feel free to raise new issues if you have questions or find any strange behaviour.

> Have a nice day !

Likewise! :]
